//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Activity.
    /// </summary>
    // *** Start programmer edit section *** (Activity CustomAttributes)

    // *** End programmer edit section *** (Activity CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ActivityE", new string[] {
            "Name as \'Name\'",
            "ActivityType as \'Activity type\'"})]
    [AssociatedDetailViewAttribute("ActivityE", "ContactInActivity", "ContactInActivityE", true, "", "Contact in activity", true, new string[] {
            ""})]
    public class Activity : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.CRM.tActivity fActivityType;
        
        private IIS.CRM.DetailArrayOfContactInActivity fContactInActivity;
        
        private IIS.CRM.Product fProduct;
        
        // *** Start programmer edit section *** (Activity CustomMembers)

        // *** End programmer edit section *** (Activity CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Activity.Name CustomAttributes)

        // *** End programmer edit section *** (Activity.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Activity.Name Get start)

                // *** End programmer edit section *** (Activity.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Activity.Name Get end)

                // *** End programmer edit section *** (Activity.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.Name Set start)

                // *** End programmer edit section *** (Activity.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Activity.Name Set end)

                // *** End programmer edit section *** (Activity.Name Set end)
            }
        }
        
        /// <summary>
        /// ActivityType.
        /// </summary>
        // *** Start programmer edit section *** (Activity.ActivityType CustomAttributes)

        // *** End programmer edit section *** (Activity.ActivityType CustomAttributes)
        public virtual IIS.CRM.tActivity ActivityType
        {
            get
            {
                // *** Start programmer edit section *** (Activity.ActivityType Get start)

                // *** End programmer edit section *** (Activity.ActivityType Get start)
                IIS.CRM.tActivity result = this.fActivityType;
                // *** Start programmer edit section *** (Activity.ActivityType Get end)

                // *** End programmer edit section *** (Activity.ActivityType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.ActivityType Set start)

                // *** End programmer edit section *** (Activity.ActivityType Set start)
                this.fActivityType = value;
                // *** Start programmer edit section *** (Activity.ActivityType Set end)

                // *** End programmer edit section *** (Activity.ActivityType Set end)
            }
        }
        
        /// <summary>
        /// Activity.
        /// </summary>
        // *** Start programmer edit section *** (Activity.ContactInActivity CustomAttributes)

        // *** End programmer edit section *** (Activity.ContactInActivity CustomAttributes)
        public virtual IIS.CRM.DetailArrayOfContactInActivity ContactInActivity
        {
            get
            {
                // *** Start programmer edit section *** (Activity.ContactInActivity Get start)

                // *** End programmer edit section *** (Activity.ContactInActivity Get start)
                if ((this.fContactInActivity == null))
                {
                    this.fContactInActivity = new IIS.CRM.DetailArrayOfContactInActivity(this);
                }
                IIS.CRM.DetailArrayOfContactInActivity result = this.fContactInActivity;
                // *** Start programmer edit section *** (Activity.ContactInActivity Get end)

                // *** End programmer edit section *** (Activity.ContactInActivity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.ContactInActivity Set start)

                // *** End programmer edit section *** (Activity.ContactInActivity Set start)
                this.fContactInActivity = value;
                // *** Start programmer edit section *** (Activity.ContactInActivity Set end)

                // *** End programmer edit section *** (Activity.ContactInActivity Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CRM.Product.
        /// </summary>
        // *** Start programmer edit section *** (Activity.Product CustomAttributes)

        // *** End programmer edit section *** (Activity.Product CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.CRM.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (Activity.Product Get start)

                // *** End programmer edit section *** (Activity.Product Get start)
                IIS.CRM.Product result = this.fProduct;
                // *** Start programmer edit section *** (Activity.Product Get end)

                // *** End programmer edit section *** (Activity.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.Product Set start)

                // *** End programmer edit section *** (Activity.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (Activity.Product Set end)

                // *** End programmer edit section *** (Activity.Product Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ActivityE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ActivityE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ActivityE", typeof(IIS.CRM.Activity));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Activity.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfActivity CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfActivity CustomAttributes)
    public class DetailArrayOfActivity : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CRM.DetailArrayOfActivity members)

        // *** End programmer edit section *** (IIS.CRM.DetailArrayOfActivity members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Activity by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Activity.
        /// </summary>
        public DetailArrayOfActivity(IIS.CRM.Product fProduct) : 
                base(typeof(Activity), ((ICSSoft.STORMNET.DataObject)(fProduct)))
        {
        }
        
        public IIS.CRM.Activity this[int index]
        {
            get
            {
                return ((IIS.CRM.Activity)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CRM.Activity dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
