//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Adminstrator.
    /// </summary>
    // *** Start programmer edit section *** (Adminstrator CustomAttributes)

    // *** End programmer edit section *** (Adminstrator CustomAttributes)
    [AutoAltered()]
    [Caption("Administrator")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AdminstratorE", new string[] {
            "Name as \'Name\'"})]
    [View("AdminstratorL", new string[] {
            "Name as \'Name\'"})]
    public class Adminstrator : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Adminstrator CustomMembers)

        // *** End programmer edit section *** (Adminstrator CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Adminstrator.Name CustomAttributes)

        // *** End programmer edit section *** (Adminstrator.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Adminstrator.Name Get start)

                // *** End programmer edit section *** (Adminstrator.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Adminstrator.Name Get end)

                // *** End programmer edit section *** (Adminstrator.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Adminstrator.Name Set start)

                // *** End programmer edit section *** (Adminstrator.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Adminstrator.Name Set end)

                // *** End programmer edit section *** (Adminstrator.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AdminstratorE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AdminstratorE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AdminstratorE", typeof(IIS.CRM.Adminstrator));
                }
            }
            
            /// <summary>
            /// "AdminstratorL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AdminstratorL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AdminstratorL", typeof(IIS.CRM.Adminstrator));
                }
            }
        }
    }
}
