//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Company.
    /// </summary>
    // *** Start programmer edit section *** (Company CustomAttributes)

    // *** End programmer edit section *** (Company CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CompanyE", new string[] {
            "Name as \'Name\'",
            "Employer as \'Employer\'",
            "Role as \'Role\'",
            "Adminstrator as \'Adminstrator\'",
            "Adminstrator.Name as \'Name\'"}, Hidden=new string[] {
            "Adminstrator.Name"})]
    [MasterViewDefineAttribute("CompanyE", "Adminstrator", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("CompanyL", new string[] {
            "Name as \'Name\'",
            "Employer as \'Employer\'",
            "Role as \'Role\'",
            "Adminstrator.Name as \'Name\'"})]
    public class Company : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fEmployer;
        
        private string fRole;
        
        private IIS.CRM.Adminstrator fAdminstrator;
        
        // *** Start programmer edit section *** (Company CustomMembers)

        // *** End programmer edit section *** (Company CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Company.Name CustomAttributes)

        // *** End programmer edit section *** (Company.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Company.Name Get start)

                // *** End programmer edit section *** (Company.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Company.Name Get end)

                // *** End programmer edit section *** (Company.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Company.Name Set start)

                // *** End programmer edit section *** (Company.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Company.Name Set end)

                // *** End programmer edit section *** (Company.Name Set end)
            }
        }
        
        /// <summary>
        /// Employer.
        /// </summary>
        // *** Start programmer edit section *** (Company.Employer CustomAttributes)

        // *** End programmer edit section *** (Company.Employer CustomAttributes)
        [StrLen(255)]
        public virtual string Employer
        {
            get
            {
                // *** Start programmer edit section *** (Company.Employer Get start)

                // *** End programmer edit section *** (Company.Employer Get start)
                string result = this.fEmployer;
                // *** Start programmer edit section *** (Company.Employer Get end)

                // *** End programmer edit section *** (Company.Employer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Company.Employer Set start)

                // *** End programmer edit section *** (Company.Employer Set start)
                this.fEmployer = value;
                // *** Start programmer edit section *** (Company.Employer Set end)

                // *** End programmer edit section *** (Company.Employer Set end)
            }
        }
        
        /// <summary>
        /// Role.
        /// </summary>
        // *** Start programmer edit section *** (Company.Role CustomAttributes)

        // *** End programmer edit section *** (Company.Role CustomAttributes)
        [StrLen(255)]
        public virtual string Role
        {
            get
            {
                // *** Start programmer edit section *** (Company.Role Get start)

                // *** End programmer edit section *** (Company.Role Get start)
                string result = this.fRole;
                // *** Start programmer edit section *** (Company.Role Get end)

                // *** End programmer edit section *** (Company.Role Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Company.Role Set start)

                // *** End programmer edit section *** (Company.Role Set start)
                this.fRole = value;
                // *** Start programmer edit section *** (Company.Role Set end)

                // *** End programmer edit section *** (Company.Role Set end)
            }
        }
        
        /// <summary>
        /// Company.
        /// </summary>
        // *** Start programmer edit section *** (Company.Adminstrator CustomAttributes)

        // *** End programmer edit section *** (Company.Adminstrator CustomAttributes)
        [NotNull()]
        public virtual IIS.CRM.Adminstrator Adminstrator
        {
            get
            {
                // *** Start programmer edit section *** (Company.Adminstrator Get start)

                // *** End programmer edit section *** (Company.Adminstrator Get start)
                IIS.CRM.Adminstrator result = this.fAdminstrator;
                // *** Start programmer edit section *** (Company.Adminstrator Get end)

                // *** End programmer edit section *** (Company.Adminstrator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Company.Adminstrator Set start)

                // *** End programmer edit section *** (Company.Adminstrator Set start)
                this.fAdminstrator = value;
                // *** Start programmer edit section *** (Company.Adminstrator Set end)

                // *** End programmer edit section *** (Company.Adminstrator Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CompanyE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CompanyE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CompanyE", typeof(IIS.CRM.Company));
                }
            }
            
            /// <summary>
            /// "CompanyL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CompanyL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CompanyL", typeof(IIS.CRM.Company));
                }
            }
        }
    }
}
