//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Contact in activity.
    /// </summary>
    // *** Start programmer edit section *** (ContactInActivity CustomAttributes)

    // *** End programmer edit section *** (ContactInActivity CustomAttributes)
    [AutoAltered()]
    [Caption("Contact In Activity")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ContactInActivityE", new string[] {
            "DateOfActivity as \'Date of activity\'",
            "Result as \'Result\'",
            "Contact as \'Contact\'",
            "Contact.Name as \'Name\'"}, Hidden=new string[] {
            "Contact.Name"})]
    [MasterViewDefineAttribute("ContactInActivityE", "Contact", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class ContactInActivity : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fDateOfActivity;
        
        private string fResult;
        
        private IIS.CRM.Contact fContact;
        
        private IIS.CRM.Activity fActivity;
        
        // *** Start programmer edit section *** (ContactInActivity CustomMembers)

        // *** End programmer edit section *** (ContactInActivity CustomMembers)

        
        /// <summary>
        /// DateOfActivity.
        /// </summary>
        // *** Start programmer edit section *** (ContactInActivity.DateOfActivity CustomAttributes)

        // *** End programmer edit section *** (ContactInActivity.DateOfActivity CustomAttributes)
        public virtual System.DateTime DateOfActivity
        {
            get
            {
                // *** Start programmer edit section *** (ContactInActivity.DateOfActivity Get start)

                // *** End programmer edit section *** (ContactInActivity.DateOfActivity Get start)
                System.DateTime result = this.fDateOfActivity;
                // *** Start programmer edit section *** (ContactInActivity.DateOfActivity Get end)

                // *** End programmer edit section *** (ContactInActivity.DateOfActivity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ContactInActivity.DateOfActivity Set start)

                // *** End programmer edit section *** (ContactInActivity.DateOfActivity Set start)
                this.fDateOfActivity = value;
                // *** Start programmer edit section *** (ContactInActivity.DateOfActivity Set end)

                // *** End programmer edit section *** (ContactInActivity.DateOfActivity Set end)
            }
        }
        
        /// <summary>
        /// Result.
        /// </summary>
        // *** Start programmer edit section *** (ContactInActivity.Result CustomAttributes)

        // *** End programmer edit section *** (ContactInActivity.Result CustomAttributes)
        [StrLen(255)]
        public virtual string Result
        {
            get
            {
                // *** Start programmer edit section *** (ContactInActivity.Result Get start)

                // *** End programmer edit section *** (ContactInActivity.Result Get start)
                string result = this.fResult;
                // *** Start programmer edit section *** (ContactInActivity.Result Get end)

                // *** End programmer edit section *** (ContactInActivity.Result Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ContactInActivity.Result Set start)

                // *** End programmer edit section *** (ContactInActivity.Result Set start)
                this.fResult = value;
                // *** Start programmer edit section *** (ContactInActivity.Result Set end)

                // *** End programmer edit section *** (ContactInActivity.Result Set end)
            }
        }
        
        /// <summary>
        /// Contact in activity.
        /// </summary>
        // *** Start programmer edit section *** (ContactInActivity.Contact CustomAttributes)

        // *** End programmer edit section *** (ContactInActivity.Contact CustomAttributes)
        [NotNull()]
        public virtual IIS.CRM.Contact Contact
        {
            get
            {
                // *** Start programmer edit section *** (ContactInActivity.Contact Get start)

                // *** End programmer edit section *** (ContactInActivity.Contact Get start)
                IIS.CRM.Contact result = this.fContact;
                // *** Start programmer edit section *** (ContactInActivity.Contact Get end)

                // *** End programmer edit section *** (ContactInActivity.Contact Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ContactInActivity.Contact Set start)

                // *** End programmer edit section *** (ContactInActivity.Contact Set start)
                this.fContact = value;
                // *** Start programmer edit section *** (ContactInActivity.Contact Set end)

                // *** End programmer edit section *** (ContactInActivity.Contact Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CRM.Activity.
        /// </summary>
        // *** Start programmer edit section *** (ContactInActivity.Activity CustomAttributes)

        // *** End programmer edit section *** (ContactInActivity.Activity CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.CRM.Activity Activity
        {
            get
            {
                // *** Start programmer edit section *** (ContactInActivity.Activity Get start)

                // *** End programmer edit section *** (ContactInActivity.Activity Get start)
                IIS.CRM.Activity result = this.fActivity;
                // *** Start programmer edit section *** (ContactInActivity.Activity Get end)

                // *** End programmer edit section *** (ContactInActivity.Activity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ContactInActivity.Activity Set start)

                // *** End programmer edit section *** (ContactInActivity.Activity Set start)
                this.fActivity = value;
                // *** Start programmer edit section *** (ContactInActivity.Activity Set end)

                // *** End programmer edit section *** (ContactInActivity.Activity Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ContactInActivityE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactInActivityE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactInActivityE", typeof(IIS.CRM.ContactInActivity));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ContactInActivity.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfContactInActivity CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfContactInActivity CustomAttributes)
    public class DetailArrayOfContactInActivity : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CRM.DetailArrayOfContactInActivity members)

        // *** End programmer edit section *** (IIS.CRM.DetailArrayOfContactInActivity members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ContactInActivity by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ContactInActivity.
        /// </summary>
        public DetailArrayOfContactInActivity(IIS.CRM.Activity fActivity) : 
                base(typeof(ContactInActivity), ((ICSSoft.STORMNET.DataObject)(fActivity)))
        {
        }
        
        public IIS.CRM.ContactInActivity this[int index]
        {
            get
            {
                return ((IIS.CRM.ContactInActivity)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CRM.ContactInActivity dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
