//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Product.
    /// </summary>
    // *** Start programmer edit section *** (Product CustomAttributes)

    // *** End programmer edit section *** (Product CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ProductE", new string[] {
            "Name as \'Name\'",
            "TypeOfProduct as \'Type of product\'",
            "Company as \'Company\'",
            "Company.Name as \'Name\'"}, Hidden=new string[] {
            "Company.Name"})]
    [AssociatedDetailViewAttribute("ProductE", "Activity", "ActivityE", true, "", "Activity", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ProductE", "Company", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("ProductL", new string[] {
            "Name as \'Name\'",
            "TypeOfProduct as \'Type of product\'",
            "Company.Name as \'Name\'"})]
    public class Product : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.CRM.tProduct fTypeOfProduct;
        
        private IIS.CRM.Company fCompany;
        
        private IIS.CRM.DetailArrayOfActivity fActivity;
        
        // *** Start programmer edit section *** (Product CustomMembers)

        // *** End programmer edit section *** (Product CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Product.Name CustomAttributes)

        // *** End programmer edit section *** (Product.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Product.Name Get start)

                // *** End programmer edit section *** (Product.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Product.Name Get end)

                // *** End programmer edit section *** (Product.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.Name Set start)

                // *** End programmer edit section *** (Product.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Product.Name Set end)

                // *** End programmer edit section *** (Product.Name Set end)
            }
        }
        
        /// <summary>
        /// TypeOfProduct.
        /// </summary>
        // *** Start programmer edit section *** (Product.TypeOfProduct CustomAttributes)

        // *** End programmer edit section *** (Product.TypeOfProduct CustomAttributes)
        public virtual IIS.CRM.tProduct TypeOfProduct
        {
            get
            {
                // *** Start programmer edit section *** (Product.TypeOfProduct Get start)

                // *** End programmer edit section *** (Product.TypeOfProduct Get start)
                IIS.CRM.tProduct result = this.fTypeOfProduct;
                // *** Start programmer edit section *** (Product.TypeOfProduct Get end)

                // *** End programmer edit section *** (Product.TypeOfProduct Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.TypeOfProduct Set start)

                // *** End programmer edit section *** (Product.TypeOfProduct Set start)
                this.fTypeOfProduct = value;
                // *** Start programmer edit section *** (Product.TypeOfProduct Set end)

                // *** End programmer edit section *** (Product.TypeOfProduct Set end)
            }
        }
        
        /// <summary>
        /// Product.
        /// </summary>
        // *** Start programmer edit section *** (Product.Company CustomAttributes)

        // *** End programmer edit section *** (Product.Company CustomAttributes)
        [NotNull()]
        public virtual IIS.CRM.Company Company
        {
            get
            {
                // *** Start programmer edit section *** (Product.Company Get start)

                // *** End programmer edit section *** (Product.Company Get start)
                IIS.CRM.Company result = this.fCompany;
                // *** Start programmer edit section *** (Product.Company Get end)

                // *** End programmer edit section *** (Product.Company Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.Company Set start)

                // *** End programmer edit section *** (Product.Company Set start)
                this.fCompany = value;
                // *** Start programmer edit section *** (Product.Company Set end)

                // *** End programmer edit section *** (Product.Company Set end)
            }
        }
        
        /// <summary>
        /// Product.
        /// </summary>
        // *** Start programmer edit section *** (Product.Activity CustomAttributes)

        // *** End programmer edit section *** (Product.Activity CustomAttributes)
        public virtual IIS.CRM.DetailArrayOfActivity Activity
        {
            get
            {
                // *** Start programmer edit section *** (Product.Activity Get start)

                // *** End programmer edit section *** (Product.Activity Get start)
                if ((this.fActivity == null))
                {
                    this.fActivity = new IIS.CRM.DetailArrayOfActivity(this);
                }
                IIS.CRM.DetailArrayOfActivity result = this.fActivity;
                // *** Start programmer edit section *** (Product.Activity Get end)

                // *** End programmer edit section *** (Product.Activity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.Activity Set start)

                // *** End programmer edit section *** (Product.Activity Set start)
                this.fActivity = value;
                // *** Start programmer edit section *** (Product.Activity Set end)

                // *** End programmer edit section *** (Product.Activity Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ProductE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ProductE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ProductE", typeof(IIS.CRM.Product));
                }
            }
            
            /// <summary>
            /// "ProductL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ProductL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ProductL", typeof(IIS.CRM.Product));
                }
            }
        }
    }
}
