//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Activity.
    /// </summary>
    // *** Start programmer edit section *** (tActivity CustomAttributes)

    // *** End programmer edit section *** (tActivity CustomAttributes)
    public enum tActivity
    {
        
        // *** Start programmer edit section *** (tActivity.Validating CustomAttributes)

        // *** End programmer edit section *** (tActivity.Validating CustomAttributes)
        [Caption("Validating")]
        Validating,
        
        // *** Start programmer edit section *** (tActivity.Sales CustomAttributes)

        // *** End programmer edit section *** (tActivity.Sales CustomAttributes)
        [Caption("Sales Call")]
        Sales,
        
        // *** Start programmer edit section *** (tActivity.Emailing CustomAttributes)

        // *** End programmer edit section *** (tActivity.Emailing CustomAttributes)
        [Caption("Emailing")]
        Emailing,
        
        // *** Start programmer edit section *** (tActivity.Interview CustomAttributes)

        // *** End programmer edit section *** (tActivity.Interview CustomAttributes)
        [Caption("Interviews")]
        Interview,
    }
}
