//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Product.
    /// </summary>
    // *** Start programmer edit section *** (tProduct CustomAttributes)

    // *** End programmer edit section *** (tProduct CustomAttributes)
    public enum tProduct
    {
        
        // *** Start programmer edit section *** (tProduct.Flexberry CustomAttributes)

        // *** End programmer edit section *** (tProduct.Flexberry CustomAttributes)
        [Caption("Flexberry AI")]
        Flexberry,
        
        // *** Start programmer edit section *** (tProduct.Designer CustomAttributes)

        // *** End programmer edit section *** (tProduct.Designer CustomAttributes)
        [Caption("Flexberry Designer")]
        Designer,
        
        // *** Start programmer edit section *** (tProduct.TeleMobis CustomAttributes)

        // *** End programmer edit section *** (tProduct.TeleMobis CustomAttributes)
        [Caption("T-Mobis")]
        TeleMobis,
    }
}
